repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff-linter
        entry: ruff
        args: [check, --fix]  
        language: system
        types: [python]
        always_run: true
        pass_filenames: false  

  - repo: local
    hooks:
      - id: add-changes
        name: "Add Changes"
        entry: bash -c 'git add -p'
        language: system
        types: [python]
