import pandas as pd


file_path = "data/test_dataset_100_100.tsv"  
data = pd.read_csv(file_path, sep='\t')


data['Hatefulness'] = data['Hatefulness'].map({'Hateful': True, 'NotHateful': False})


data['Hatefulness'] = data['Hatefulness'].astype(bool)


updated_output_file_path = "data/test_dataset_100_100.tsv"
data.to_csv(updated_output_file_path, sep='\t', index=False)
print(f"Updated dataset with True/False saved to {updated_output_file_path}.")


context_dict = {
    "erxitcw": "Criticizes double standards in judgment based on gender roles.",
    "ek3e7e4": "Reflects on corruption and dysfunction in administrative systems.",
    "amm0tv-title": "Provocative and explicit comment on inappropriate behavior.",
    "erxp18u": "Neutral explanation about a specific subgenre of content.",
    "ekodsn6": "Casual commentary about differing opinions on a social platform.",
    "bavb8x-post": "Narrates a personal story of kindness and giving to the less fortunate.",
    "ethidsy": "Dramatic and extreme reaction to an illness.",
    "bgycq3-title": "Questioning the legality and morality of certain legal situations.",
    "eikkhnc": "Expressing surprise or irony at a specific event.",
    "eflbfb3": "Agreement or affirmation, context unclear without more detail.",
    "eo1bky5": "Generic comment showing amazement or surprise.",
    "ejmrvke": "Query about an application or tool.",
    "eiica8w": "Conversation about loneliness and self-improvement, slightly humorous.",
    "efsko6v": "Brief, negative comment about fear of women.",
    "epndxyv": "Casual reference to a past event or memory.",
    "ek86s4e": "Discussion about immigration and political ideologies.",
    "egt7y37": "Provocative and inappropriate slur.",
    "ervrcj5": "Comment about interpretations and themes in literature.",
    "epjkvyc": "Politically charged comment with strong opinions.",
    "egb4fae": "Criticism of online behavior, particularly from certain groups.",
    "eqhkn6v": "Observation about voting behavior.",
    "eoib3mi": "Humorous comment about a simple mistake.",
    "ehan49q": "Observation about a historical figure’s actions.",
    "enxn5kb": "Brief affirmation, context unclear.",
    "embwvku": "Highly offensive and inappropriate comment.",
    "etmr2cf": "Negative comment about personal habits.",
    "emn3qef": "Blaming a group for perceived societal issues.",
    "etarhbz": "Racially charged and offensive comment.",
    "ek5s31v": "Query about a subreddit or group.",
    "et4nq4u": "Comment about subreddit moderation policies.",
    "elbk8mc": "Humorous observation about future generations.",
    "et4zh3i": "Comment about censorship and societal views.",
    "emyyy94": "Discussion about propaganda and its sources.",
    "eo1fbdd": "Provocative comment about skin color and its impact.",
    "ekidqk5": "Discussion about gaming culture and its implications.",
    "ekavmfw": "Promoting a community with specific content.",
    "eryqke9": "Casual, humorous comment.",
    "eklo0g6": "Dismissive or sarcastic reaction to an argument.",
    "epeq5yv": "Discussion about gender roles and societal expectations.",
    "eia8pzj": "Offensive racial slur.",
    "es79jvx": "Highly inflammatory and politically charged statement.",
    "epi4z37": "Satirical comment about political ideologies.",
    "eijpa4s": "Insult directed at an individual.",
    "esav3vh": "Humorous observation about societal habits.",
    "eqqa4qw": "Question about time investment in online platforms.",
    "blg8l7-title": "Comment about generational behavior.",
    "embuqo7": "Offensive and derogatory remark.",
    "ehjjpt7": "Inappropriate comment about a sexual situation.",
    "et58tyh": "Comment on personal beliefs and their impact on behavior.",
    "bfgsmg-post": "Extended rant about dissatisfaction with online platforms.",
    "ep4at92": "Humorous, sarcastic comment.",
    "ehj8dfw": "Philosophical question about morality.",
    "eq0k7sc": "Offensive insult targeting an individual.",
    "emc16lx": "Casual affirmation of an online interaction.",
    "emzax1r": "Discussion about corporate control over financial tools.",
    "esknr14": "Criticism of societal norms and their implications.",
    "elomawg": "Dismissive response to a comment.",
    "ekxz6me": "Satirical commentary about political correctness.",
    "ehd6ygd": "Casual comment about personal finances.",
    "cb8ow4-title": "Casual comment about generational trends.",
    "emnwswl": "Comment about art critique and behavior.",
    "eslolco": "Offensive insult targeting an individual.",
    "eruxrfk": "Observation about racial biases in content.",
    "ek6ast3": "Criticism of moderation in online communities.",
    "eii2xih": "Extended discussion about a controversial individual.",
    "eof6v3x": "Negative opinion about a group or behavior.",
    "es9z2xi": "Politically charged comment about minority groups.",
    "eil90r3": "Comment about education and knowledge.",
    "efl69lw": "Humorous, self-deprecating comment.",
    "ejdcofy": "Observation about typical behavior in a subreddit.",
    "efkq4yi": "Humorous exclamation.",
    "eikvrv7": "Comment about moderation practices.",
    "ega56at": "Casual observation about an event.",
    "eoia1vg": "Dismissive comment about a behavior.",
    "eg7o162": "Humorous comment about decision-making.",
    "egh089l": "Satirical comment about societal inequality.",
    "egtb043": "Inappropriate and offensive comment about explicit content.",
    "esnozsj": "Humorous remark about political power.",
    "enu0gq9": "Recommendation for browsing habits.",
    "bbovsh-title": "Philosophical comment about morality.",
    "epjp7ku": "Religious or cultural observation.",
    "emsu60k": "Criticism of platform policies and practices.",
    "es82lzw": "Brief comment about psychological understanding.",
    "emech8i": "Casual acknowledgment.",
    "ej8d0im": "Discussion about consumer choice in online platforms.",
    "entu03s": "Statistical observation with a hint of humor.",
    "etnxj40": "Humorous misinterpretation.",
    "efl6zk0": "Self-deprecating comment with a humorous tone.",
    "eozcj9m": "Criticism of seeking validation online.",
    "es7v9om": "Extended comment on societal decline.",
    "ens2vc3": "Comment about societal double standards.",
    "ehbj2g6": "Reference to controversial incidents.",
    "eg54g7t": "Observation about societal hypocrisy.",
    "erxxqzb": "Casual opinion about friendship dynamics.",
    "elt7r8q": "Dismissive comment about political ideologies.",
    "eh9u6zg": "Imaginative thought experiment.",
    "epobt75": "Casual question about a technical topic.",
    "egvk763": "Discussion about fandom and nostalgia.",
    "embo3xn": "Humorous comment about niche preferences.",
    "egi8swp": "Casual praise or humor.",
    "etfbzwn": "Brief retort.",
    "egt6ykr": "Highly offensive comment.",
    "bml9mb-title": "Observation about political affiliations.",
    "eoex9vj": "Personal opinion about movies.",
    "em4jrdo": "Casual comment.",
    "efstfl2": "Criticism of competitive behavior.",
    "eubp4tv": "Humorous but inappropriate comment.",
    "efl0x9q": "Humorous acknowledgment of a phobia.",
    "erxm4wg": "Positive acknowledgment.",
    "etmjwqf": "Humorous exaggeration.",
    "erycfsp": "Comment about art criticism.",
    "bjvozi-title": "Offensive remark targeting a group.",
    "bhjtv6-title": "Criticism of online censorship.",
    "erybbax": "Comment with regional context.",
    "esb41nq": "Inappropriate remark.",
    "err0axp": "Casual observation about a subreddit.",
    "eoihbj8": "Highly offensive comment.",
    "eqffruq": "Playful, humorous remark.",
    "emzb28b": "Casual question about a change in text.",
    "es7ugpr": "Criticism of behavior and attitudes.",
    "egh71p2": "Highly offensive comment.",
    "eivqp7r": "Humorous parody of a song.",
    "elpfuht": "Criticism of societal changes.",
    "err0jy1": "Comment about a subreddit’s rules.",
    "enu9vfz": "Criticism of specific groups.",
    "ertfa5q": "Dismissive comment about actions of groups.",
    "ei2i38k": "Satirical comment about legal decisions.",
    "eo1toea": "Comment about societal segregation.",
    "eubsz9l": "Offensive racial stereotype.",
    "eg8thok": "Inappropriate and offensive comment.",
    "ervtcic": "Philosophical comment about meaning in texts.",
    "ekzavef": "Comment on societal privileges.",
    "eqg1z85": "Comment about a humorous misunderstanding.",
    "bzeawu-title": "Casual question about a topic.",
    "etm94or": "Comment questioning cultural norms.",
    "eflge06": "Humorous or self-referential comment.",
    "epkcvyc": "Criticism of online discourse.",
    "brpvne-post": "Discussion about social detachment in online culture.",
    "eryqaha": "Comment about cultural communication.",
    "eqqsd31": "Casual response to a guess.",
    "emz8zpf": "Criticism of corporate coercion.",
    "etawdz3": "Humorous comment about confusion.",
    "erxmzi6": "Interpretation of a situation.",
    "epz4flr": "Criticism of political ideologies.",
    "ephar55": "Politically charged comment.",
    "esij7cb": "Highly offensive remark.",
    "efnc7yq": "Humorous comment.",
    "epmjhg9": "Discussion about healthcare policies.",
    "efsizck": "Casual, humorous remark.",
    "et562p7": "Provocative and inflammatory question.",
    "etmh7u5": "Comment with inappropriate language.",
    "etmlnid": "Affirmation, context unclear.",
    "eu6jwtf": "Criticism of group dynamics.",
    "eiso90v": "Comment about a public figure.",
    "ettjsd5": "Humorous remark about social norms.",
    "ekbgfty": "Criticism of political ideologies.",
    "en027uf": "Observation about historical parallels.",
    "cb04dx-title": "Humorous observation.",
    "esob3d6": "Criticism of double standards.",
    "ephaclp": "Criticism of political events and media.",
    "eiho6hi": "Comment about societal standards.",
    "epjc95a": "Discussion about political issues.",
    "es36p1t": "Humorous comment about a photoshoot.",
    "ek6xrna": "Discussion about community actions.",
    "eokc1t8": "Humorous and self-referential.",
    "elxhb21": "Controversial comment about religion.",
    "em8sjt9": "Casual question about a link.",
    "c93pxu-title": "Criticism of platform moderation.",
    "et3f2kp": "Humorous comment about habits.",
    "ep2su0d": "Criticism of group dynamics.",
    "em9k7lb": "Discussion about societal rhetoric.",
    "ekc8xxh": "Criticism of platform moderation.",
    "esaohdt": "Inappropriate remark.",
    "eple649": "Politically charged comment.",
    "egh3bco": "Link to content, unclear context.",
    "efsngqf": "Humorous comeback.",
    "erzgw2l": "Expression of confusion.",
    "ep0dp73": "Criticism of hate and online behavior.",
    "esaow9i": "Humorous, nonsensical remark.",
    "eookcqh": "Expression of confusion.",
    "eikxsde": "Comment about societal changes.",
    "es3xijn": "Extended critique of societal and corporate policies.",
    "ek8b2nt": "Discussion about gaming features.",
    "egx334t": "Positive interpretation of fan content.",
    "efuq62g": "Humorous observation.",
    "egt6t9e": "Philosophical humor about nature.",
    "efsa04y": "Inappropriate and offensive remark.",
    "ek6gjid": "Criticism of mental well-being.",
    "ek84x14": "Criticism of societal biases.",
    "eikuq70": "Brief agreement.",
    "eggvs07": "Highly offensive comment.",
    "eiktyfw": "Discussion about contrasting viewpoints.",
    "enrva8h": "Highly offensive remark.",
    "eh960qe": "Humorous question.",
    "epaa70n": "Criticism of societal attitudes.",
    "ep4onmk": "Observation about grammar.",
    "esiqsjy": "Highly offensive and inappropriate comment.",
    "eogo074": "Humorous satirical remark.",
    "etrfam0": "Expression of belonging.",
    "esadadk": "Acknowledgment of group dynamics.",
}

# Add a "Context" column to the DataFrame using the dictionary
data['Context'] = data['id'].map(context_dict)

# Handle cases where no context is found
data['Context'] = data['Context'].fillna("Context not available")

# Save the updated dataset with contexts added
context_output_file_path = "data/test_dataset_100_100.tsv_with_context.tsv"
data.to_csv(context_output_file_path, sep='\t', index=False)
print(f"Dataset with contexts added saved to {context_output_file_path}.")